In [2]:
import torch
import numpy as np

C:\Users\Fatihi\.conda\envs\Pytorch_1\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# Initializing from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

# From a NumPy Array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

# From another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
x_rand = torch.rand_like(x_data, dtype = torch.float) # overrides the datatype of x_data
print(f"\nOnes Tensor: \n{x_ones} \nRandom Tensor: \n{x_rand} \n")

# With random or constant values:
'''Shape is a tuple of tensor dimensions'''
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n{rand_tensor} \nOnes Tensor: \n{ones_tensor} \nZeros Tensor: \n{zeros_tensor}")

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

Ones Tensor: 
tensor([[1, 1],
        [1, 1]]) 
Random Tensor: 
tensor([[0.0503, 0.1256],
        [0.3595, 0.2704]]) 

Random Tensor: 
tensor([[0.0363, 0.2474, 0.4729],
        [0.7089, 0.9606, 0.5128]]) 
Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# ATTRIBUTES OF A TENSOR

#Tensor attributes describe their shape, datatype, and the device on which they are stored
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}\nDatatype of tensor: {tensor.dtype}\nDevice tensor is stored on:{tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on:cpu


Over 100 tensor operations, including arithmetic, linear algerba, matrix manipalutaion(transposing, indexing, slicing), sampling and more can be found in __[here](https://pytorch.org/docs/stable/torch.html)__

Each of these operations can be run on the GPU. By default, tensors are created on the CPU.
We need to explicitly move tensors to the GPU using .to method(after checking GPU availability)
We should keep in mind that copying large tensors across devices can be expensive in terms of time and memory.

In [14]:
# OPERATIONS ON TENSORS

# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

# Standard numpy-like indexing and slicing:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

tensor[:,1] = 0
print(tensor)

# Joining tensors with torch.cat to concatenate a sequence of tensors along a given dimension. torch.stack can also be used to join tensors that's subtly different from torch.cat
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f"\n{t1}\n")

# Arithmetic operations
# This computes the matrix multiplication between two tensors. y1,y2,y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor

# We calculate the matrix product of `tensor` and its transpose `tensor.T` using @, which is the equivalent to calling matmul()
y1 = tensor @ tensor.T
# same as the statement above, but we're calling matmul() directly instead of @ operator.
y2 = tensor.matmul(tensor.T)
# We create a random tensor of the same shape as the result of the matrix multiplication of `tensor` and `tensor.T`
y3 = torch.rand_like(y1)
# We performs the same matrix multiplication as the first two lines but specifies the output tensor `y3` for the result of the operation using the `out` parameter of the `matmul()`
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(f"z1 {z1}, \nz2 {z2}\n")
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out = z3)

# Single-element tensors if you have a one-element tensor, like aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item()
# We calculate the sum of all the element in `tensor` using sum() method, assigned to `agg` 
agg = tensor.sum()
# we extract the value of the sum, which convert the sum tensor to a Python scalar value.
agg_item = agg.item()
print(agg_item, type(agg_item))

# In-place operations operations that store the result into the operand are called in-place. denoted by a _ suffix
# for example: x.copy_(y), x.t_(), will change x
print(f"{tensor}\n")
tensor.add_(5)
print(tensor)
''' 
In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history.
Hence, their use is discouraged
'''


First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

z1 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]), 
z2 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

12.0 <class 'float'>
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [17]:
#BRIDGE WITH NumPy
#Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other

# Tensor to NumPy array
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
# A change in the tensor reflects in the NumPy array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

# NumPy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n)
# Changes in the NumPy array reflects in the tensor
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
